// <auto-generated />
using System;
using CleanChat.Infrastructure.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanChat.API.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20230513062035_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanChat.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "chau",
                            Password = "123"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "dai",
                            Password = "123"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "tuananh",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.ClientTopic", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("ClientTopics");
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TopicId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            TopicName = "A"
                        },
                        new
                        {
                            TopicId = 2,
                            TopicName = "B"
                        },
                        new
                        {
                            TopicId = 3,
                            TopicName = "C"
                        });
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.ClientTopic", b =>
                {
                    b.HasOne("CleanChat.Domain.Entities.Client", "Client")
                        .WithMany("ClientTopics")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanChat.Domain.Entities.Topic", "Topic")
                        .WithMany("ClientTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.Message", b =>
                {
                    b.HasOne("CleanChat.Domain.Entities.Client", "Client")
                        .WithMany("Messages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanChat.Domain.Entities.Topic", "Topic")
                        .WithMany("Messages")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.Client", b =>
                {
                    b.Navigation("ClientTopics");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CleanChat.Domain.Entities.Topic", b =>
                {
                    b.Navigation("ClientTopics");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
